"""empty message

Revision ID: 308474da8cbc
Revises: e722bc2ef80d
Create Date: 2023-02-06 20:33:02.374476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '308474da8cbc'
down_revision = 'e722bc2ef80d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=False))
        batch_op.create_unique_constraint("email", ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint("email", type_='unique')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
